import type {
  AzId,
  CameraShot,
  NodeDef,
  NodeId,
  StoryBeat,
  TxStatus,
  Vec3,
  ViewId,
} from "./types";

export const REGION = {
  id: "ap-south-1",
  city: "Mumbai",
  label: "ap-south-1  ·  Mumbai",
};

export const AZ_META: {
  id: AzId;
  x: number;
  code: string;
  zone: string;
}[] = [
  { id: "az-1", x: -12, code: "AZ-01", zone: "ap-south-1a" },
  { id: "az-2", x: 0, code: "AZ-02", zone: "ap-south-1b" },
  { id: "az-3", x: 12, code: "AZ-03", zone: "ap-south-1c" },
];

export const POS = {
  client: [0, 3.1, 30] as Vec3,
  cloudfront: [0, 4.2, 23.5] as Vec3,
  route53: [0, 6.4, 20.2] as Vec3,
  waf: [0, 3.5, 15.6] as Vec3,
  apigateway: [0, 3.8, 12.4] as Vec3,
  cognito: [-4.6, 3.3, 7.4] as Vec3,
  kms: [4.6, 3.5, 7.4] as Vec3,
  lambda: [0, 2.6, 2.0] as Vec3,
  sqs: [0, 2.3, -3.8] as Vec3,
  dynamodb: [0, 3.0, -9.4] as Vec3,
  settlement: [0, 2.7, -15.4] as Vec3,
  cloudwatch: [-8.4, 11.2, 1.5] as Vec3,
  xray: [0, 12.4, 1.2] as Vec3,
  quicksight: [8.4, 11.2, 1.5] as Vec3,
};

export const CF_POPS: Vec3[] = [
  [-19, 3.2, 22.5],
  [-11.5, 4.1, 24.6],
  [-4.2, 4.8, 25.4],
  [4.2, 4.8, 25.4],
  [11.5, 4.1, 24.6],
  [19, 3.2, 22.5],
];

export const NODES: Record<NodeId, NodeDef> = {
  client: {
    id: "client",
    name: "Client Layer",
    aws: "Payer & Payee",
    layer: "Client",
    role: "Initiates and receives UPI payment intents from devices at the edge of the system.",
    behavior: "Devices emit signed payment requests and await confirmation packets.",
    scaling: "Horizontally unlimited at the client; constrained by edge capacity.",
    connected: ["CloudFront", "Route 53"],
    latency: "Device RTT",
    costLabel: "Client",
    costNote: "Not billed — illustrative",
    color: "blue",
    position: POS.client,
    inspect: { position: [6, 6, 38], target: POS.client },
    collider: [8, 4, 4],
  },
  cloudfront: {
    id: "cloudfront",
    name: "Amazon CloudFront",
    aws: "CloudFront",
    layer: "Edge",
    role: "Global edge delivery. Terminates TLS close to the user and forwards to origin.",
    behavior: "Anycast PoPs absorb traffic, cache idempotent reads, and origin-shield writes.",
    scaling: "PoP-level elastic bandwidth; regional spillover under surge.",
    connected: ["Route 53", "WAF", "API Gateway"],
    latency: "8–18 ms",
    costLabel: "Edge Delivery",
    costNote: "Illustrative / simulated",
    color: "orange",
    position: POS.cloudfront,
    inspect: { position: [10, 8, 32], target: POS.cloudfront },
    collider: [22, 6, 6],
  },
  route53: {
    id: "route53",
    name: "Amazon Route 53",
    aws: "Route 53",
    layer: "Edge",
    role: "Intelligent DNS routing. Directs each request to a healthy edge and region.",
    behavior: "Latency-based and health-checked records; failover to surviving endpoints.",
    scaling: "Anycast control plane; no application-level scale knob.",
    connected: ["CloudFront", "API Gateway"],
    latency: "4–12 ms",
    costLabel: "DNS / Routing",
    costNote: "Illustrative / simulated",
    color: "orange",
    position: POS.route53,
    inspect: { position: [7, 10, 26], target: POS.route53 },
    collider: [4, 4, 4],
  },
  waf: {
    id: "waf",
    name: "AWS WAF",
    aws: "WAF",
    layer: "Security",
    role: "Protective perimeter. Inspects and filters requests before they reach APIs.",
    behavior: "Rule groups drop volumetric abuse, injected payloads, and unsigned traffic.",
    scaling: "Edge-enforced; capacity tracks CloudFront.",
    connected: ["CloudFront", "API Gateway"],
    latency: "1–3 ms",
    costLabel: "Perimeter",
    costNote: "Illustrative / simulated",
    color: "red",
    position: POS.waf,
    inspect: { position: [8, 6, 22], target: POS.waf },
    collider: [10, 5, 2.5],
  },
  apigateway: {
    id: "apigateway",
    name: "Amazon API Gateway",
    aws: "API Gateway",
    layer: "API",
    role: "Regional front door. Authenticates, throttles, and fans requests into compute.",
    behavior: "HTTP APIs with usage plans, request validation, and stage-level routing.",
    scaling: "Managed; per-account burst then smooth.",
    connected: ["WAF", "Cognito", "Lambda", "CloudWatch"],
    latency: "6–15 ms",
    costLabel: "API",
    costNote: "Illustrative / simulated",
    color: "orange",
    position: POS.apigateway,
    inspect: { position: [9, 7, 20], target: POS.apigateway },
    collider: [8, 6, 5],
  },
  cognito: {
    id: "cognito",
    name: "Amazon Cognito",
    aws: "Cognito",
    layer: "Security",
    role: "Identity chamber. Issues and verifies tokens for payer, payee, and PSP actors.",
    behavior: "JWT issuance, device fingerprint, and certificate-backed 2FA challenges.",
    scaling: "User-pool elastic; token minting parallelizes under load.",
    connected: ["API Gateway", "KMS", "Lambda"],
    latency: "12–28 ms",
    costLabel: "Identity",
    costNote: "Illustrative / simulated",
    color: "orange",
    position: POS.cognito,
    inspect: { position: [-10, 6, 14], target: POS.cognito },
    collider: [4.5, 5, 4.5],
  },
  kms: {
    id: "kms",
    name: "AWS KMS",
    aws: "KMS",
    layer: "Security",
    role: "Cryptographic root. Encrypts payloads, signs settlements, wraps data keys.",
    behavior: "Envelope encryption; CMKs never leave HSM boundary.",
    scaling: "Key-ops throttling with retry-safe client SDKs.",
    connected: ["Cognito", "Lambda", "DynamoDB"],
    latency: "3–8 ms",
    costLabel: "Encryption",
    costNote: "Illustrative / simulated",
    color: "orange",
    position: POS.kms,
    inspect: { position: [11, 6, 14], target: POS.kms },
    collider: [4.2, 5, 4.2],
  },
  lambda: {
    id: "lambda",
    name: "AWS Lambda",
    aws: "Lambda",
    layer: "Processing",
    role: "Serverless compute for authorization, risk, and posting logic.",
    behavior: "Event-driven execution. Instances appear under load and freeze when idle.",
    scaling: "Auto, per-request. Concurrency rises with inbound TPS.",
    connected: ["API Gateway", "SQS", "DynamoDB", "KMS"],
    latency: "8–22 ms",
    costLabel: "Compute",
    costNote: "Illustrative / simulated",
    color: "cyan",
    position: POS.lambda,
    inspect: { position: [12, 8, 10], target: POS.lambda },
    collider: [28, 5, 6],
  },
  sqs: {
    id: "sqs",
    name: "Amazon SQS",
    aws: "SQS",
    layer: "Messaging",
    role: "Durable buffer between request path and asynchronous posting.",
    behavior: "Messages enqueue, wait, and delete after successful processing.",
    scaling: "Near-unlimited depth; backpressure surfaces as queue age.",
    connected: ["Lambda", "DynamoDB", "CloudWatch"],
    latency: "Queue wait",
    costLabel: "Messaging",
    costNote: "Illustrative / simulated",
    color: "cyan",
    position: POS.sqs,
    inspect: { position: [12, 7, 4], target: POS.sqs },
    collider: [28, 4, 5],
  },
  dynamodb: {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    aws: "DynamoDB",
    layer: "Ledger",
    role: "Distributed ledger of intents, holds, and posted entries.",
    behavior: "Partitioned storage with synchronized write pulses across AZs.",
    scaling: "On-demand capacity. Partitions split as keys heat up.",
    connected: ["Lambda", "SQS", "KMS", "Settlement"],
    latency: "4–12 ms",
    costLabel: "Database",
    costNote: "Illustrative / simulated",
    color: "blue",
    position: POS.dynamodb,
    inspect: { position: [14, 8, -2], target: POS.dynamodb },
    collider: [28, 7, 6],
  },
  settlement: {
    id: "settlement",
    name: "Settlement Core",
    aws: "Step Functions + DynamoDB",
    layer: "Settlement",
    role: "Finality. Debit, credit, and emit confirmation once the ledger agrees.",
    behavior: "Idempotent posting with compensating rollback on partial failure.",
    scaling: "Orchestrated; bounded by ledger write capacity.",
    connected: ["DynamoDB", "API Gateway", "X-Ray"],
    latency: "15–40 ms",
    costLabel: "Orchestration",
    costNote: "Illustrative / simulated",
    color: "green",
    position: POS.settlement,
    inspect: { position: [10, 7, -8], target: POS.settlement },
    collider: [8, 5, 6],
  },
  cloudwatch: {
    id: "cloudwatch",
    name: "Amazon CloudWatch",
    aws: "CloudWatch",
    layer: "Observability",
    role: "Metrics, logs, and alarms across every hop of the payment path.",
    behavior: "Time-series scrape of RPS, latency, errors, and queue depth.",
    scaling: "Ingestion elastic; dashboards are query-side.",
    connected: ["Lambda", "API Gateway", "SQS", "QuickSight"],
    latency: "Metric delay ~1s",
    costLabel: "Telemetry",
    costNote: "Illustrative / simulated",
    color: "purple",
    position: POS.cloudwatch,
    inspect: { position: [-14, 14, 10], target: POS.cloudwatch },
    collider: [5, 5, 5],
  },
  xray: {
    id: "xray",
    name: "AWS X-Ray",
    aws: "X-Ray",
    layer: "Observability",
    role: "Distributed tracing. Reconstructs one transaction across services.",
    behavior: "Segment documents stitched into a service graph per trace id.",
    scaling: "Sampled under high TPS; full traces on demand.",
    connected: ["API Gateway", "Lambda", "DynamoDB", "Settlement"],
    latency: "Trace flush",
    costLabel: "Tracing",
    costNote: "Illustrative / simulated",
    color: "purple",
    position: POS.xray,
    inspect: { position: [6, 16, 12], target: POS.xray },
    collider: [4, 5, 4],
  },
  quicksight: {
    id: "quicksight",
    name: "Amazon QuickSight",
    aws: "QuickSight",
    layer: "Observability",
    role: "Analytics surface. Turns operational telemetry into human-readable structure.",
    behavior: "SPICE extracts over CloudWatch and ledger aggregates.",
    scaling: "Reader sessions independent of the payment data plane.",
    connected: ["CloudWatch", "DynamoDB"],
    latency: "Batch",
    costLabel: "Analytics",
    costNote: "Illustrative / simulated",
    color: "purple",
    position: POS.quicksight,
    inspect: { position: [14, 14, 10], target: POS.quicksight },
    collider: [5, 5, 5],
  },
};

export const NODE_LIST = Object.values(NODES);

export const VIEWS: Record<ViewId, CameraShot> = {
  overview: { position: [20, 15, 34], target: [0, 1.6, 4] },
  payment: { position: [9.5, 7.2, 19], target: [0, 2.6, 5] },
  security: { position: [9, 6.5, 16], target: [0, 3.2, 10] },
  data: { position: [15, 8.5, -3], target: [0, 2.2, -8] },
  observability: { position: [5, 18, 16], target: [0, 9.5, 2] },
  ha: { position: [0.2, 28, 14], target: [0, 0.4, -2] },
};

export const INTRO_SHOT: CameraShot = {
  position: [0, 52, 92],
  target: [0, 0.2, 2],
};

export const STORY: StoryBeat[] = [
  {
    index: 1,
    kicker: "Section 01",
    title: "The Payment",
    body: "A single authorization moves from the device through edge, identity, compute, queue, ledger, and back as confirmation.",
    view: "payment",
    sim: "payment",
  },
  {
    index: 2,
    kicker: "Section 02",
    title: "The Edge",
    body: "Route 53 directs the request. CloudFront terminates it near the user. API Gateway becomes the regional front door.",
    view: "payment",
  },
  {
    index: 3,
    kicker: "Section 03",
    title: "The Processing Layer",
    body: "Lambda executes the business path. SQS absorbs burst. DynamoDB records intent with single-digit millisecond writes.",
    view: "data",
  },
  {
    index: 4,
    kicker: "Section 04",
    title: "The Security Layer",
    body: "WAF filters the perimeter. Cognito proves identity, including certificate-backed 2FA. KMS wraps every sensitive payload.",
    view: "security",
  },
  {
    index: 5,
    kicker: "Section 05",
    title: "The Distributed System",
    body: "Three availability zones run in parallel. Lose one and traffic redistributes. Auto-scaling and failover are the architecture, not an afterthought.",
    view: "ha",
    sim: "failure",
  },
  {
    index: 6,
    kicker: "Section 06",
    title: "Observability",
    body: "CloudWatch records the pulse. X-Ray reconstructs a single trace. QuickSight turns the stream into a picture a human can read.",
    view: "observability",
    sim: "trace",
  },
  {
    index: 7,
    kicker: "Section 07",
    title: "The Complete System",
    body: "Edge, identity, compute, ledger, and observation as one spatial machine. This is the shape of a national-scale payment rail.",
    view: "overview",
  },
];

export const LAYERS = [
  { id: "client", label: "Client", z: 30 },
  { id: "edge", label: "Edge", z: 23 },
  { id: "api", label: "API", z: 13 },
  { id: "auth", label: "Auth", z: 7.4 },
  { id: "compute", label: "Compute", z: 2 },
  { id: "queue", label: "Queue", z: -3.8 },
  { id: "ledger", label: "Ledger", z: -9.4 },
  { id: "settle", label: "Settle", z: -15.4 },
] as const;

export const LOADING_STAGES = [
  "Initializing architecture",
  "Loading compute nodes",
  "Establishing network",
  "Initializing data layer",
  "Starting simulation",
] as const;

/** Primary hop sequence used by the hero transaction. */
export const PAYMENT_HOPS: NodeId[] = [
  "client",
  "cloudfront",
  "route53",
  "waf",
  "apigateway",
  "cognito",
  "kms",
  "lambda",
  "sqs",
  "dynamodb",
  "settlement",
  "apigateway",
  "client",
];

export const HOP_STATUS: TxStatus[] = [
  "INITIATING",
  "ROUTING",
  "ROUTING",
  "ROUTING",
  "ROUTING",
  "AUTHENTICATING",
  "AUTHENTICATING",
  "PROCESSING",
  "QUEUED",
  "WRITING",
  "SETTLING",
  "CONFIRMING",
  "CONFIRMED",
];

export function azPosition(id: NodeId, az: AzId): Vec3 {
  const base = NODES[id].position;
  if (id === "lambda" || id === "sqs" || id === "dynamodb") {
    const meta = AZ_META.find((a) => a.id === az)!;
    return [meta.x, base[1], base[2]];
  }
  return base;
}

export const CONNECTIONS: [NodeId, NodeId][] = [
  ["client", "cloudfront"],
  ["cloudfront", "route53"],
  ["route53", "waf"],
  ["cloudfront", "waf"],
  ["waf", "apigateway"],
  ["apigateway", "cognito"],
  ["apigateway", "kms"],
  ["cognito", "kms"],
  ["apigateway", "lambda"],
  ["cognito", "lambda"],
  ["kms", "lambda"],
  ["lambda", "sqs"],
  ["sqs", "dynamodb"],
  ["lambda", "dynamodb"],
  ["dynamodb", "settlement"],
  ["settlement", "apigateway"],
  ["lambda", "cloudwatch"],
  ["apigateway", "cloudwatch"],
  ["sqs", "cloudwatch"],
  ["settlement", "xray"],
  ["lambda", "xray"],
  ["cloudwatch", "quicksight"],
  ["dynamodb", "quicksight"],
];

export const ACCENT: Record<NodeDef["color"], string> = {
  orange: "#ff9900",
  blue: "#4f8cff",
  green: "#3ee0a0",
  red: "#ff5a57",
  purple: "#b794f6",
  cyan: "#3db9ff",
};
